using KabadaAPIdao;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace KabadaAPI {
  partial class DAcontext {
    private void AddData_NACE(ModelBuilder modelBuilder) {
      Guid g=new Guid();

      g=ind(modelBuilder, @"A", @"Agriculture, forestry and fishing");
        act(modelBuilder, g, @"A.01", @"Crop and animal production, hunting and related service activities");
        act(modelBuilder, g, @"A.01.1", @"Growing of non-perennial crops");
        act(modelBuilder, g, @"A.01.11", @"Growing of cereals (except rice), leguminous crops and oil seeds");
        act(modelBuilder, g, @"A.01.12", @"Growing of rice");
        act(modelBuilder, g, @"A.01.13", @"Growing of vegetables and melons, roots and tubers");
        act(modelBuilder, g, @"A.01.14", @"Growing of sugar cane");
        act(modelBuilder, g, @"A.01.15", @"Growing of tobacco");
        act(modelBuilder, g, @"A.01.16", @"Growing of fibre crops");
        act(modelBuilder, g, @"A.01.19", @"Growing of other non-perennial crops");
        act(modelBuilder, g, @"A.01.2", @"Growing of perennial crops");
        act(modelBuilder, g, @"A.01.21", @"Growing of grapes");
        act(modelBuilder, g, @"A.01.22", @"Growing of tropical and subtropical fruits");
        act(modelBuilder, g, @"A.01.23", @"Growing of citrus fruits");
        act(modelBuilder, g, @"A.01.24", @"Growing of pome fruits and stone fruits");
        act(modelBuilder, g, @"A.01.25", @"Growing of other tree and bush fruits and nuts");
        act(modelBuilder, g, @"A.01.26", @"Growing of oleaginous fruits");
        act(modelBuilder, g, @"A.01.27", @"Growing of beverage crops");
        act(modelBuilder, g, @"A.01.28", @"Growing of spices, aromatic, drug and pharmaceutical crops");
        act(modelBuilder, g, @"A.01.29", @"Growing of other perennial crops");
        act(modelBuilder, g, @"A.01.3", @"Plant propagation");
        act(modelBuilder, g, @"A.01.30", @"Plant propagation");
        act(modelBuilder, g, @"A.01.4", @"Animal production");
        act(modelBuilder, g, @"A.01.41", @"Raising of dairy cattle");
        act(modelBuilder, g, @"A.01.42", @"Raising of other cattle and buffaloes");
        act(modelBuilder, g, @"A.01.43", @"Raising of horses and other equines");
        act(modelBuilder, g, @"A.01.44", @"Raising of camels and camelids");
        act(modelBuilder, g, @"A.01.45", @"Raising of sheep and goats");
        act(modelBuilder, g, @"A.01.46", @"Raising of swine/pigs");
        act(modelBuilder, g, @"A.01.47", @"Raising of poultry");
        act(modelBuilder, g, @"A.01.49", @"Raising of other animals");
        act(modelBuilder, g, @"A.01.5", @"Mixed farming");
        act(modelBuilder, g, @"A.01.50", @"Mixed farming");
        act(modelBuilder, g, @"A.01.6", @"Support activities to agriculture and post-harvest crop activities");
        act(modelBuilder, g, @"A.01.61", @"Support activities for crop production");
        act(modelBuilder, g, @"A.01.62", @"Support activities for animal production");
        act(modelBuilder, g, @"A.01.63", @"Post-harvest crop activities");
        act(modelBuilder, g, @"A.01.64", @"Seed processing for propagation");
        act(modelBuilder, g, @"A.01.7", @"Hunting, trapping and related service activities");
        act(modelBuilder, g, @"A.01.70", @"Hunting, trapping and related service activities");
        act(modelBuilder, g, @"A.02", @"Forestry and logging");
        act(modelBuilder, g, @"A.02.1", @"Silviculture and other forestry activities");
        act(modelBuilder, g, @"A.02.10", @"Silviculture and other forestry activities");
        act(modelBuilder, g, @"A.02.2", @"Logging");
        act(modelBuilder, g, @"A.02.20", @"Logging");
        act(modelBuilder, g, @"A.02.3", @"Gathering of wild growing non-wood products");
        act(modelBuilder, g, @"A.02.30", @"Gathering of wild growing non-wood products");
        act(modelBuilder, g, @"A.02.4", @"Support services to forestry");
        act(modelBuilder, g, @"A.02.40", @"Support services to forestry");
        act(modelBuilder, g, @"A.03", @"Fishing and aquaculture");
        act(modelBuilder, g, @"A.03.1", @"Fishing");
        act(modelBuilder, g, @"A.03.11", @"Marine fishing");
        act(modelBuilder, g, @"A.03.12", @"Freshwater fishing");
        act(modelBuilder, g, @"A.03.2", @"Aquaculture");
        act(modelBuilder, g, @"A.03.21", @"Marine aquaculture");
        act(modelBuilder, g, @"A.03.22", @"Freshwater aquaculture");

      g=ind(modelBuilder, @"B", @"Mining and quarrying");
        act(modelBuilder, g, @"B.05", @"Mining of coal and lignite");
        act(modelBuilder, g, @"B.05.1", @"Mining of hard coal");
        act(modelBuilder, g, @"B.05.10", @"Mining of hard coal");
        act(modelBuilder, g, @"B.05.2", @"Mining of lignite");
        act(modelBuilder, g, @"B.05.20", @"Mining of lignite");
        act(modelBuilder, g, @"B.06", @"Extraction of crude petroleum and natural gas");
        act(modelBuilder, g, @"B.06.1", @"Extraction of crude petroleum");
        act(modelBuilder, g, @"B.06.10", @"Extraction of crude petroleum");
        act(modelBuilder, g, @"B.06.2", @"Extraction of natural gas");
        act(modelBuilder, g, @"B.06.20", @"Extraction of natural gas");
        act(modelBuilder, g, @"B.07", @"Mining of metal ores");
        act(modelBuilder, g, @"B.07.1", @"Mining of iron ores");
        act(modelBuilder, g, @"B.07.10", @"Mining of iron ores");
        act(modelBuilder, g, @"B.07.2", @"Mining of non-ferrous metal ores");
        act(modelBuilder, g, @"B.07.21", @"Mining of uranium and thorium ores");
        act(modelBuilder, g, @"B.07.29", @"Mining of other non-ferrous metal ores");
        act(modelBuilder, g, @"B.08", @"Other mining and quarrying");
        act(modelBuilder, g, @"B.08.1", @"Quarrying of stone, sand and clay");
        act(modelBuilder, g, @"B.08.11", @"Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate");
        act(modelBuilder, g, @"B.08.12", @"Operation of gravel and sand pits; mining of clays and kaolin");
        act(modelBuilder, g, @"B.08.9", @"Mining and quarrying n.e.c.");
        act(modelBuilder, g, @"B.08.91", @"Mining of chemical and fertiliser minerals");
        act(modelBuilder, g, @"B.08.92", @"Extraction of peat");
        act(modelBuilder, g, @"B.08.93", @"Extraction of salt");
        act(modelBuilder, g, @"B.08.99", @"Other mining and quarrying n.e.c.");
        act(modelBuilder, g, @"B.09", @"Mining support service activities");
        act(modelBuilder, g, @"B.09.1", @"Support activities for petroleum and natural gas extraction");
        act(modelBuilder, g, @"B.09.10", @"Support activities for petroleum and natural gas extraction");
        act(modelBuilder, g, @"B.09.9", @"Support activities for other mining and quarrying");
        act(modelBuilder, g, @"B.09.90", @"Support activities for other mining and quarrying");

      g=ind(modelBuilder, @"C", @"Manufacturing");
        act(modelBuilder, g, @"C.10", @"Manufacture of food products");
        act(modelBuilder, g, @"C.10.1", @"Processing and preserving of meat and production of meat products");
        act(modelBuilder, g, @"C.10.11", @"Processing and preserving of meat");
        act(modelBuilder, g, @"C.10.12", @"Processing and preserving of poultry meat");
        act(modelBuilder, g, @"C.10.13", @"Production of meat and poultry meat products");
        act(modelBuilder, g, @"C.10.2", @"Processing and preserving of fish, crustaceans and molluscs");
        act(modelBuilder, g, @"C.10.20", @"Processing and preserving of fish, crustaceans and molluscs");
        act(modelBuilder, g, @"C.10.3", @"Processing and preserving of fruit and vegetables");
        act(modelBuilder, g, @"C.10.31", @"Processing and preserving of potatoes");
        act(modelBuilder, g, @"C.10.32", @"Manufacture of fruit and vegetable juice");
        act(modelBuilder, g, @"C.10.39", @"Other processing and preserving of fruit and vegetables");
        act(modelBuilder, g, @"C.10.4", @"Manufacture of vegetable and animal oils and fats");
        act(modelBuilder, g, @"C.10.41", @"Manufacture of oils and fats");
        act(modelBuilder, g, @"C.10.42", @"Manufacture of margarine and similar edible fats");
        act(modelBuilder, g, @"C.10.5", @"Manufacture of dairy products");
        act(modelBuilder, g, @"C.10.51", @"Operation of dairies and cheese making");
        act(modelBuilder, g, @"C.10.52", @"Manufacture of ice cream");
        act(modelBuilder, g, @"C.10.6", @"Manufacture of grain mill products, starches and starch products");
        act(modelBuilder, g, @"C.10.61", @"Manufacture of grain mill products");
        act(modelBuilder, g, @"C.10.62", @"Manufacture of starches and starch products");
        act(modelBuilder, g, @"C.10.7", @"Manufacture of bakery and farinaceous products");
        act(modelBuilder, g, @"C.10.71", @"Manufacture of bread; manufacture of fresh pastry goods and cakes");
        act(modelBuilder, g, @"C.10.72", @"Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes");
        act(modelBuilder, g, @"C.10.73", @"Manufacture of macaroni, noodles, couscous and similar farinaceous products");
        act(modelBuilder, g, @"C.10.8", @"Manufacture of other food products");
        act(modelBuilder, g, @"C.10.81", @"Manufacture of sugar");
        act(modelBuilder, g, @"C.10.82", @"Manufacture of cocoa, chocolate and sugar confectionery");
        act(modelBuilder, g, @"C.10.83", @"Processing of tea and coffee");
        act(modelBuilder, g, @"C.10.84", @"Manufacture of condiments and seasonings");
        act(modelBuilder, g, @"C.10.85", @"Manufacture of prepared meals and dishes");
        act(modelBuilder, g, @"C.10.86", @"Manufacture of homogenised food preparations and dietetic food");
        act(modelBuilder, g, @"C.10.89", @"Manufacture of other food products n.e.c.");
        act(modelBuilder, g, @"C.10.9", @"Manufacture of prepared animal feeds");
        act(modelBuilder, g, @"C.10.91", @"Manufacture of prepared feeds for farm animals");
        act(modelBuilder, g, @"C.10.92", @"Manufacture of prepared pet foods");
        act(modelBuilder, g, @"C.11", @"Manufacture of beverages");
        act(modelBuilder, g, @"C.11.0", @"Manufacture of beverages");
        act(modelBuilder, g, @"C.11.01", @"Distilling, rectifying and blending of spirits");
        act(modelBuilder, g, @"C.11.02", @"Manufacture of wine from grape");
        act(modelBuilder, g, @"C.11.03", @"Manufacture of cider and other fruit wines");
        act(modelBuilder, g, @"C.11.04", @"Manufacture of other non-distilled fermented beverages");
        act(modelBuilder, g, @"C.11.05", @"Manufacture of beer");
        act(modelBuilder, g, @"C.11.06", @"Manufacture of malt");
        act(modelBuilder, g, @"C.11.07", @"Manufacture of soft drinks; production of mineral waters and other bottled waters");
        act(modelBuilder, g, @"C.12", @"Manufacture of tobacco products");
        act(modelBuilder, g, @"C.12.0", @"Manufacture of tobacco products");
        act(modelBuilder, g, @"C.12.00", @"Manufacture of tobacco products");
        act(modelBuilder, g, @"C.13", @"Manufacture of textiles");
        act(modelBuilder, g, @"C.13.1", @"Preparation and spinning of textile fibres");
        act(modelBuilder, g, @"C.13.10", @"Preparation and spinning of textile fibres");
        act(modelBuilder, g, @"C.13.2", @"Weaving of textiles");
        act(modelBuilder, g, @"C.13.20", @"Weaving of textiles");
        act(modelBuilder, g, @"C.13.3", @"Finishing of textiles");
        act(modelBuilder, g, @"C.13.30", @"Finishing of textiles");
        act(modelBuilder, g, @"C.13.9", @"Manufacture of other textiles");
        act(modelBuilder, g, @"C.13.91", @"Manufacture of knitted and crocheted fabrics");
        act(modelBuilder, g, @"C.13.92", @"Manufacture of made-up textile articles, except apparel");
        act(modelBuilder, g, @"C.13.93", @"Manufacture of carpets and rugs");
        act(modelBuilder, g, @"C.13.94", @"Manufacture of cordage, rope, twine and netting");
        act(modelBuilder, g, @"C.13.95", @"Manufacture of non-wovens and articles made from non-wovens, except apparel");
        act(modelBuilder, g, @"C.13.96", @"Manufacture of other technical and industrial textiles");
        act(modelBuilder, g, @"C.13.99", @"Manufacture of other textiles n.e.c.");
        act(modelBuilder, g, @"C.14", @"Manufacture of wearing apparel");
        act(modelBuilder, g, @"C.14.1", @"Manufacture of wearing apparel, except fur apparel");
        act(modelBuilder, g, @"C.14.11", @"Manufacture of leather clothes");
        act(modelBuilder, g, @"C.14.12", @"Manufacture of workwear");
        act(modelBuilder, g, @"C.14.13", @"Manufacture of other outerwear");
        act(modelBuilder, g, @"C.14.14", @"Manufacture of underwear");
        act(modelBuilder, g, @"C.14.19", @"Manufacture of other wearing apparel and accessories");
        act(modelBuilder, g, @"C.14.2", @"Manufacture of articles of fur");
        act(modelBuilder, g, @"C.14.20", @"Manufacture of articles of fur");
        act(modelBuilder, g, @"C.14.3", @"Manufacture of knitted and crocheted apparel");
        act(modelBuilder, g, @"C.14.31", @"Manufacture of knitted and crocheted hosiery");
        act(modelBuilder, g, @"C.14.39", @"Manufacture of other knitted and crocheted apparel");
        act(modelBuilder, g, @"C.15", @"Manufacture of leather and related products");
        act(modelBuilder, g, @"C.15.1", @"Tanning and dressing of leather; manufacture of luggage, handbags, saddlery and harness; dressing and dyeing of fur");
        act(modelBuilder, g, @"C.15.11", @"Tanning and dressing of leather; dressing and dyeing of fur");
        act(modelBuilder, g, @"C.15.12", @"Manufacture of luggage, handbags and the like, saddlery and harness");
        act(modelBuilder, g, @"C.15.2", @"Manufacture of footwear");
        act(modelBuilder, g, @"C.15.20", @"Manufacture of footwear");
        act(modelBuilder, g, @"C.16", @"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials");
        act(modelBuilder, g, @"C.16.1", @"Sawmilling and planing of wood");
        act(modelBuilder, g, @"C.16.10", @"Sawmilling and planing of wood");
        act(modelBuilder, g, @"C.16.2", @"Manufacture of products of wood, cork, straw and plaiting materials");
        act(modelBuilder, g, @"C.16.21", @"Manufacture of veneer sheets and wood-based panels");
        act(modelBuilder, g, @"C.16.22", @"Manufacture of assembled parquet floors");
        act(modelBuilder, g, @"C.16.23", @"Manufacture of other builders' carpentry and joinery");
        act(modelBuilder, g, @"C.16.24", @"Manufacture of wooden containers");
        act(modelBuilder, g, @"C.16.29", @"Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials");
        act(modelBuilder, g, @"C.17", @"Manufacture of paper and paper products");
        act(modelBuilder, g, @"C.17.1", @"Manufacture of pulp, paper and paperboard");
        act(modelBuilder, g, @"C.17.11", @"Manufacture of pulp");
        act(modelBuilder, g, @"C.17.12", @"Manufacture of paper and paperboard");
        act(modelBuilder, g, @"C.17.2", @"Manufacture of articles of paper and paperboard");
        act(modelBuilder, g, @"C.17.21", @"Manufacture of corrugated paper and paperboard and of containers of paper and paperboard");
        act(modelBuilder, g, @"C.17.22", @"Manufacture of household and sanitary goods and of toilet requisites");
        act(modelBuilder, g, @"C.17.23", @"Manufacture of paper stationery");
        act(modelBuilder, g, @"C.17.24", @"Manufacture of wallpaper");
        act(modelBuilder, g, @"C.17.29", @"Manufacture of other articles of paper and paperboard");
        act(modelBuilder, g, @"C.18", @"Printing and reproduction of recorded media");
        act(modelBuilder, g, @"C.18.1", @"Printing and service activities related to printing");
        act(modelBuilder, g, @"C.18.11", @"Printing of newspapers");
        act(modelBuilder, g, @"C.18.12", @"Other printing");
        act(modelBuilder, g, @"C.18.13", @"Pre-press and pre-media services");
        act(modelBuilder, g, @"C.18.14", @"Binding and related services");
        act(modelBuilder, g, @"C.18.2", @"Reproduction of recorded media");
        act(modelBuilder, g, @"C.18.20", @"Reproduction of recorded media");
        act(modelBuilder, g, @"C.19", @"Manufacture of coke and refined petroleum products");
        act(modelBuilder, g, @"C.19.1", @"Manufacture of coke oven products");
        act(modelBuilder, g, @"C.19.10", @"Manufacture of coke oven products");
        act(modelBuilder, g, @"C.19.2", @"Manufacture of refined petroleum products");
        act(modelBuilder, g, @"C.19.20", @"Manufacture of refined petroleum products");
        act(modelBuilder, g, @"C.20", @"Manufacture of chemicals and chemical products");
        act(modelBuilder, g, @"C.20.1", @"Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms");
        act(modelBuilder, g, @"C.20.11", @"Manufacture of industrial gases");
        act(modelBuilder, g, @"C.20.12", @"Manufacture of dyes and pigments");
        act(modelBuilder, g, @"C.20.13", @"Manufacture of other inorganic basic chemicals");
        act(modelBuilder, g, @"C.20.14", @"Manufacture of other organic basic chemicals");
        act(modelBuilder, g, @"C.20.15", @"Manufacture of fertilisers and nitrogen compounds");
        act(modelBuilder, g, @"C.20.16", @"Manufacture of plastics in primary forms");
        act(modelBuilder, g, @"C.20.17", @"Manufacture of synthetic rubber in primary forms");
        act(modelBuilder, g, @"C.20.2", @"Manufacture of pesticides and other agrochemical products");
        act(modelBuilder, g, @"C.20.20", @"Manufacture of pesticides and other agrochemical products");
        act(modelBuilder, g, @"C.20.3", @"Manufacture of paints, varnishes and similar coatings, printing ink and mastics");
        act(modelBuilder, g, @"C.20.30", @"Manufacture of paints, varnishes and similar coatings, printing ink and mastics");
        act(modelBuilder, g, @"C.20.4", @"Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations");
        act(modelBuilder, g, @"C.20.41", @"Manufacture of soap and detergents, cleaning and polishing preparations");
        act(modelBuilder, g, @"C.20.42", @"Manufacture of perfumes and toilet preparations");
        act(modelBuilder, g, @"C.20.5", @"Manufacture of other chemical products");
        act(modelBuilder, g, @"C.20.51", @"Manufacture of explosives");
        act(modelBuilder, g, @"C.20.52", @"Manufacture of glues");
        act(modelBuilder, g, @"C.20.53", @"Manufacture of essential oils");
        act(modelBuilder, g, @"C.20.59", @"Manufacture of other chemical products n.e.c.");
        act(modelBuilder, g, @"C.20.6", @"Manufacture of man-made fibres");
        act(modelBuilder, g, @"C.20.60", @"Manufacture of man-made fibres");
        act(modelBuilder, g, @"C.21", @"Manufacture of basic pharmaceutical products and pharmaceutical preparations");
        act(modelBuilder, g, @"C.21.1", @"Manufacture of basic pharmaceutical products");
        act(modelBuilder, g, @"C.21.10", @"Manufacture of basic pharmaceutical products");
        act(modelBuilder, g, @"C.21.2", @"Manufacture of pharmaceutical preparations");
        act(modelBuilder, g, @"C.21.20", @"Manufacture of pharmaceutical preparations");
        act(modelBuilder, g, @"C.22", @"Manufacture of rubber and plastic products");
        act(modelBuilder, g, @"C.22.1", @"Manufacture of rubber products");
        act(modelBuilder, g, @"C.22.11", @"Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres");
        act(modelBuilder, g, @"C.22.19", @"Manufacture of other rubber products");
        act(modelBuilder, g, @"C.22.2", @"Manufacture of plastics products");
        act(modelBuilder, g, @"C.22.21", @"Manufacture of plastic plates, sheets, tubes and profiles");
        act(modelBuilder, g, @"C.22.22", @"Manufacture of plastic packing goods");
        act(modelBuilder, g, @"C.22.23", @"Manufacture of builders’ ware of plastic");
        act(modelBuilder, g, @"C.22.29", @"Manufacture of other plastic products");
        act(modelBuilder, g, @"C.23", @"Manufacture of other non-metallic mineral products");
        act(modelBuilder, g, @"C.23.1", @"Manufacture of glass and glass products");
        act(modelBuilder, g, @"C.23.11", @"Manufacture of flat glass");
        act(modelBuilder, g, @"C.23.12", @"Shaping and processing of flat glass");
        act(modelBuilder, g, @"C.23.13", @"Manufacture of hollow glass");
        act(modelBuilder, g, @"C.23.14", @"Manufacture of glass fibres");
        act(modelBuilder, g, @"C.23.19", @"Manufacture and processing of other glass, including technical glassware");
        act(modelBuilder, g, @"C.23.2", @"Manufacture of refractory products");
        act(modelBuilder, g, @"C.23.20", @"Manufacture of refractory products");
        act(modelBuilder, g, @"C.23.3", @"Manufacture of clay building materials");
        act(modelBuilder, g, @"C.23.31", @"Manufacture of ceramic tiles and flags");
        act(modelBuilder, g, @"C.23.32", @"Manufacture of bricks, tiles and construction products, in baked clay");
        act(modelBuilder, g, @"C.23.4", @"Manufacture of other porcelain and ceramic products");
        act(modelBuilder, g, @"C.23.41", @"Manufacture of ceramic household and ornamental articles");
        act(modelBuilder, g, @"C.23.42", @"Manufacture of ceramic sanitary fixtures");
        act(modelBuilder, g, @"C.23.43", @"Manufacture of ceramic insulators and insulating fittings");
        act(modelBuilder, g, @"C.23.44", @"Manufacture of other technical ceramic products");
        act(modelBuilder, g, @"C.23.49", @"Manufacture of other ceramic products");
        act(modelBuilder, g, @"C.23.5", @"Manufacture of cement, lime and plaster");
        act(modelBuilder, g, @"C.23.51", @"Manufacture of cement");
        act(modelBuilder, g, @"C.23.52", @"Manufacture of lime and plaster");
        act(modelBuilder, g, @"C.23.6", @"Manufacture of articles of concrete, cement and plaster");
        act(modelBuilder, g, @"C.23.61", @"Manufacture of concrete products for construction purposes");
        act(modelBuilder, g, @"C.23.62", @"Manufacture of plaster products for construction purposes");
        act(modelBuilder, g, @"C.23.63", @"Manufacture of ready-mixed concrete");
        act(modelBuilder, g, @"C.23.64", @"Manufacture of mortars");
        act(modelBuilder, g, @"C.23.65", @"Manufacture of fibre cement");
        act(modelBuilder, g, @"C.23.69", @"Manufacture of other articles of concrete, plaster and cement");
        act(modelBuilder, g, @"C.23.7", @"Cutting, shaping and finishing of stone");
        act(modelBuilder, g, @"C.23.70", @"Cutting, shaping and finishing of stone");
        act(modelBuilder, g, @"C.23.9", @"Manufacture of abrasive products and non-metallic mineral products n.e.c.");
        act(modelBuilder, g, @"C.23.91", @"Production of abrasive products");
        act(modelBuilder, g, @"C.23.99", @"Manufacture of other non-metallic mineral products n.e.c.");
        act(modelBuilder, g, @"C.24", @"Manufacture of basic metals");
        act(modelBuilder, g, @"C.24.1", @"Manufacture of basic iron and steel and of ferro-alloys");
        act(modelBuilder, g, @"C.24.10", @"Manufacture of basic iron and steel and of ferro-alloys");
        act(modelBuilder, g, @"C.24.2", @"Manufacture of tubes, pipes, hollow profiles and related fittings, of steel");
        act(modelBuilder, g, @"C.24.20", @"Manufacture of tubes, pipes, hollow profiles and related fittings, of steel");
        act(modelBuilder, g, @"C.24.3", @"Manufacture of other products of first processing of steel");
        act(modelBuilder, g, @"C.24.31", @"Cold drawing of bars");
        act(modelBuilder, g, @"C.24.32", @"Cold rolling of narrow strip");
        act(modelBuilder, g, @"C.24.33", @"Cold forming or folding");
        act(modelBuilder, g, @"C.24.34", @"Cold drawing of wire");
        act(modelBuilder, g, @"C.24.4", @"Manufacture of basic precious and other non-ferrous metals");
        act(modelBuilder, g, @"C.24.41", @"Precious metals production");
        act(modelBuilder, g, @"C.24.42", @"Aluminium production");
        act(modelBuilder, g, @"C.24.43", @"Lead, zinc and tin production");
        act(modelBuilder, g, @"C.24.44", @"Copper production");
        act(modelBuilder, g, @"C.24.45", @"Other non-ferrous metal production");
        act(modelBuilder, g, @"C.24.46", @"Processing of nuclear fuel");
        act(modelBuilder, g, @"C.24.5", @"Casting of metals");
        act(modelBuilder, g, @"C.24.51", @"Casting of iron");
        act(modelBuilder, g, @"C.24.52", @"Casting of steel");
        act(modelBuilder, g, @"C.24.53", @"Casting of light metals");
        act(modelBuilder, g, @"C.24.54", @"Casting of other non-ferrous metals");
        act(modelBuilder, g, @"C.25", @"Manufacture of fabricated metal products, except machinery and equipment");
        act(modelBuilder, g, @"C.25.1", @"Manufacture of structural metal products");
        act(modelBuilder, g, @"C.25.11", @"Manufacture of metal structures and parts of structures");
        act(modelBuilder, g, @"C.25.12", @"Manufacture of doors and windows of metal");
        act(modelBuilder, g, @"C.25.2", @"Manufacture of tanks, reservoirs and containers of metal");
        act(modelBuilder, g, @"C.25.21", @"Manufacture of central heating radiators and boilers");
        act(modelBuilder, g, @"C.25.29", @"Manufacture of other tanks, reservoirs and containers of metal");
        act(modelBuilder, g, @"C.25.3", @"Manufacture of steam generators, except central heating hot water boilers");
        act(modelBuilder, g, @"C.25.30", @"Manufacture of steam generators, except central heating hot water boilers");
        act(modelBuilder, g, @"C.25.4", @"Manufacture of weapons and ammunition");
        act(modelBuilder, g, @"C.25.40", @"Manufacture of weapons and ammunition");
        act(modelBuilder, g, @"C.25.5", @"Forging, pressing, stamping and roll-forming of metal; powder metallurgy");
        act(modelBuilder, g, @"C.25.50", @"Forging, pressing, stamping and roll-forming of metal; powder metallurgy");
        act(modelBuilder, g, @"C.25.6", @"Treatment and coating of metals; machining");
        act(modelBuilder, g, @"C.25.61", @"Treatment and coating of metals");
        act(modelBuilder, g, @"C.25.62", @"Machining");
        act(modelBuilder, g, @"C.25.7", @"Manufacture of cutlery, tools and general hardware");
        act(modelBuilder, g, @"C.25.71", @"Manufacture of cutlery");
        act(modelBuilder, g, @"C.25.72", @"Manufacture of locks and hinges");
        act(modelBuilder, g, @"C.25.73", @"Manufacture of tools");
        act(modelBuilder, g, @"C.25.9", @"Manufacture of other fabricated metal products");
        act(modelBuilder, g, @"C.25.91", @"Manufacture of steel drums and similar containers");
        act(modelBuilder, g, @"C.25.92", @"Manufacture of light metal packaging");
        act(modelBuilder, g, @"C.25.93", @"Manufacture of wire products, chain and springs");
        act(modelBuilder, g, @"C.25.94", @"Manufacture of fasteners and screw machine products");
        act(modelBuilder, g, @"C.25.99", @"Manufacture of other fabricated metal products n.e.c.");
        act(modelBuilder, g, @"C.26", @"Manufacture of computer, electronic and optical products");
        act(modelBuilder, g, @"C.26.1", @"Manufacture of electronic components and boards");
        act(modelBuilder, g, @"C.26.11", @"Manufacture of electronic components");
        act(modelBuilder, g, @"C.26.12", @"Manufacture of loaded electronic boards");
        act(modelBuilder, g, @"C.26.2", @"Manufacture of computers and peripheral equipment");
        act(modelBuilder, g, @"C.26.20", @"Manufacture of computers and peripheral equipment");
        act(modelBuilder, g, @"C.26.3", @"Manufacture of communication equipment");
        act(modelBuilder, g, @"C.26.30", @"Manufacture of communication equipment");
        act(modelBuilder, g, @"C.26.4", @"Manufacture of consumer electronics");
        act(modelBuilder, g, @"C.26.40", @"Manufacture of consumer electronics");
        act(modelBuilder, g, @"C.26.5", @"Manufacture of instruments and appliances for measuring, testing and navigation; watches and clocks");
        act(modelBuilder, g, @"C.26.51", @"Manufacture of instruments and appliances for measuring, testing and navigation");
        act(modelBuilder, g, @"C.26.52", @"Manufacture of watches and clocks");
        act(modelBuilder, g, @"C.26.6", @"Manufacture of irradiation, electromedical and electrotherapeutic equipment");
        act(modelBuilder, g, @"C.26.60", @"Manufacture of irradiation, electromedical and electrotherapeutic equipment");
        act(modelBuilder, g, @"C.26.7", @"Manufacture of optical instruments and photographic equipment");
        act(modelBuilder, g, @"C.26.70", @"Manufacture of optical instruments and photographic equipment");
        act(modelBuilder, g, @"C.26.8", @"Manufacture of magnetic and optical media");
        act(modelBuilder, g, @"C.26.80", @"Manufacture of magnetic and optical media");
        act(modelBuilder, g, @"C.27", @"Manufacture of electrical equipment");
        act(modelBuilder, g, @"C.27.1", @"Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus");
        act(modelBuilder, g, @"C.27.11", @"Manufacture of electric motors, generators and transformers");
        act(modelBuilder, g, @"C.27.12", @"Manufacture of electricity distribution and control apparatus");
        act(modelBuilder, g, @"C.27.2", @"Manufacture of batteries and accumulators");
        act(modelBuilder, g, @"C.27.20", @"Manufacture of batteries and accumulators");
        act(modelBuilder, g, @"C.27.3", @"Manufacture of wiring and wiring devices");
        act(modelBuilder, g, @"C.27.31", @"Manufacture of fibre optic cables");
        act(modelBuilder, g, @"C.27.32", @"Manufacture of other electronic and electric wires and cables");
        act(modelBuilder, g, @"C.27.33", @"Manufacture of wiring devices");
        act(modelBuilder, g, @"C.27.4", @"Manufacture of electric lighting equipment");
        act(modelBuilder, g, @"C.27.40", @"Manufacture of electric lighting equipment");
        act(modelBuilder, g, @"C.27.5", @"Manufacture of domestic appliances");
        act(modelBuilder, g, @"C.27.51", @"Manufacture of electric domestic appliances");
        act(modelBuilder, g, @"C.27.52", @"Manufacture of non-electric domestic appliances");
        act(modelBuilder, g, @"C.27.9", @"Manufacture of other electrical equipment");
        act(modelBuilder, g, @"C.27.90", @"Manufacture of other electrical equipment");
        act(modelBuilder, g, @"C.28", @"Manufacture of machinery and equipment n.e.c.");
        act(modelBuilder, g, @"C.28.1", @"Manufacture of general-purpose machinery");
        act(modelBuilder, g, @"C.28.11", @"Manufacture of engines and turbines, except aircraft, vehicle and cycle engines");
        act(modelBuilder, g, @"C.28.12", @"Manufacture of fluid power equipment");
        act(modelBuilder, g, @"C.28.13", @"Manufacture of other pumps and compressors");
        act(modelBuilder, g, @"C.28.14", @"Manufacture of other taps and valves");
        act(modelBuilder, g, @"C.28.15", @"Manufacture of bearings, gears, gearing and driving elements");
        act(modelBuilder, g, @"C.28.2", @"Manufacture of other general-purpose machinery");
        act(modelBuilder, g, @"C.28.21", @"Manufacture of ovens, furnaces and furnace burners");
        act(modelBuilder, g, @"C.28.22", @"Manufacture of lifting and handling equipment");
        act(modelBuilder, g, @"C.28.23", @"Manufacture of office machinery and equipment (except computers and peripheral equipment)");
        act(modelBuilder, g, @"C.28.24", @"Manufacture of power-driven hand tools");
        act(modelBuilder, g, @"C.28.25", @"Manufacture of non-domestic cooling and ventilation equipment");
        act(modelBuilder, g, @"C.28.29", @"Manufacture of other general-purpose machinery n.e.c.");
        act(modelBuilder, g, @"C.28.3", @"Manufacture of agricultural and forestry machinery");
        act(modelBuilder, g, @"C.28.30", @"Manufacture of agricultural and forestry machinery");
        act(modelBuilder, g, @"C.28.4", @"Manufacture of metal forming machinery and machine tools");
        act(modelBuilder, g, @"C.28.41", @"Manufacture of metal forming machinery");
        act(modelBuilder, g, @"C.28.49", @"Manufacture of other machine tools");
        act(modelBuilder, g, @"C.28.9", @"Manufacture of other special-purpose machinery");
        act(modelBuilder, g, @"C.28.91", @"Manufacture of machinery for metallurgy");
        act(modelBuilder, g, @"C.28.92", @"Manufacture of machinery for mining, quarrying and construction");
        act(modelBuilder, g, @"C.28.93", @"Manufacture of machinery for food, beverage and tobacco processing");
        act(modelBuilder, g, @"C.28.94", @"Manufacture of machinery for textile, apparel and leather production");
        act(modelBuilder, g, @"C.28.95", @"Manufacture of machinery for paper and paperboard production");
        act(modelBuilder, g, @"C.28.96", @"Manufacture of plastics and rubber machinery");
        act(modelBuilder, g, @"C.28.99", @"Manufacture of other special-purpose machinery n.e.c.");
        act(modelBuilder, g, @"C.29", @"Manufacture of motor vehicles, trailers and semi-trailers");
        act(modelBuilder, g, @"C.29.1", @"Manufacture of motor vehicles");
        act(modelBuilder, g, @"C.29.10", @"Manufacture of motor vehicles");
        act(modelBuilder, g, @"C.29.2", @"Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers");
        act(modelBuilder, g, @"C.29.20", @"Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers");
        act(modelBuilder, g, @"C.29.3", @"Manufacture of parts and accessories for motor vehicles");
        act(modelBuilder, g, @"C.29.31", @"Manufacture of electrical and electronic equipment for motor vehicles");
        act(modelBuilder, g, @"C.29.32", @"Manufacture of other parts and accessories for motor vehicles");
        act(modelBuilder, g, @"C.30", @"Manufacture of other transport equipment");
        act(modelBuilder, g, @"C.30.1", @"Building of ships and boats");
        act(modelBuilder, g, @"C.30.11", @"Building of ships and floating structures");
        act(modelBuilder, g, @"C.30.12", @"Building of pleasure and sporting boats");
        act(modelBuilder, g, @"C.30.2", @"Manufacture of railway locomotives and rolling stock");
        act(modelBuilder, g, @"C.30.20", @"Manufacture of railway locomotives and rolling stock");
        act(modelBuilder, g, @"C.30.3", @"Manufacture of air and spacecraft and related machinery");
        act(modelBuilder, g, @"C.30.30", @"Manufacture of air and spacecraft and related machinery");
        act(modelBuilder, g, @"C.30.4", @"Manufacture of military fighting vehicles");
        act(modelBuilder, g, @"C.30.40", @"Manufacture of military fighting vehicles");
        act(modelBuilder, g, @"C.30.9", @"Manufacture of transport equipment n.e.c.");
        act(modelBuilder, g, @"C.30.91", @"Manufacture of motorcycles");
        act(modelBuilder, g, @"C.30.92", @"Manufacture of bicycles and invalid carriages");
        act(modelBuilder, g, @"C.30.99", @"Manufacture of other transport equipment n.e.c.");
        act(modelBuilder, g, @"C.31", @"Manufacture of furniture");
        act(modelBuilder, g, @"C.31.0", @"Manufacture of furniture");
        act(modelBuilder, g, @"C.31.01", @"Manufacture of office and shop furniture");
        act(modelBuilder, g, @"C.31.02", @"Manufacture of kitchen furniture");
        act(modelBuilder, g, @"C.31.03", @"Manufacture of mattresses");
        act(modelBuilder, g, @"C.31.09", @"Manufacture of other furniture");
        act(modelBuilder, g, @"C.32", @"Other manufacturing");
        act(modelBuilder, g, @"C.32.1", @"Manufacture of jewellery, bijouterie and related articles");
        act(modelBuilder, g, @"C.32.11", @"Striking of coins");
        act(modelBuilder, g, @"C.32.12", @"Manufacture of jewellery and related articles");
        act(modelBuilder, g, @"C.32.13", @"Manufacture of imitation jewellery and related articles");
        act(modelBuilder, g, @"C.32.2", @"Manufacture of musical instruments");
        act(modelBuilder, g, @"C.32.20", @"Manufacture of musical instruments");
        act(modelBuilder, g, @"C.32.3", @"Manufacture of sports goods");
        act(modelBuilder, g, @"C.32.30", @"Manufacture of sports goods");
        act(modelBuilder, g, @"C.32.4", @"Manufacture of games and toys");
        act(modelBuilder, g, @"C.32.40", @"Manufacture of games and toys");
        act(modelBuilder, g, @"C.32.5", @"Manufacture of medical and dental instruments and supplies");
        act(modelBuilder, g, @"C.32.50", @"Manufacture of medical and dental instruments and supplies");
        act(modelBuilder, g, @"C.32.9", @"Manufacturing n.e.c.");
        act(modelBuilder, g, @"C.32.91", @"Manufacture of brooms and brushes");
        act(modelBuilder, g, @"C.32.99", @"Other manufacturing n.e.c.");
        act(modelBuilder, g, @"C.33", @"Repair and installation of machinery and equipment");
        act(modelBuilder, g, @"C.33.1", @"Repair of fabricated metal products, machinery and equipment");
        act(modelBuilder, g, @"C.33.11", @"Repair of fabricated metal products");
        act(modelBuilder, g, @"C.33.12", @"Repair of machinery");
        act(modelBuilder, g, @"C.33.13", @"Repair of electronic and optical equipment");
        act(modelBuilder, g, @"C.33.14", @"Repair of electrical equipment");
        act(modelBuilder, g, @"C.33.15", @"Repair and maintenance of ships and boats");
        act(modelBuilder, g, @"C.33.16", @"Repair and maintenance of aircraft and spacecraft");
        act(modelBuilder, g, @"C.33.17", @"Repair and maintenance of other transport equipment");
        act(modelBuilder, g, @"C.33.19", @"Repair of other equipment");
        act(modelBuilder, g, @"C.33.2", @"Installation of industrial machinery and equipment");
        act(modelBuilder, g, @"C.33.20", @"Installation of industrial machinery and equipment");

      g=ind(modelBuilder, @"D", @"Electricity, gas, steam and air conditioning supply");
        act(modelBuilder, g, @"D.35", @"Electricity, gas, steam and air conditioning supply");
        act(modelBuilder, g, @"D.35.1", @"Electric power generation, transmission and distribution");
        act(modelBuilder, g, @"D.35.11", @"Production of electricity");
        act(modelBuilder, g, @"D.35.12", @"Transmission of electricity");
        act(modelBuilder, g, @"D.35.13", @"Distribution of electricity");
        act(modelBuilder, g, @"D.35.14", @"Trade of electricity");
        act(modelBuilder, g, @"D.35.2", @"Manufacture of gas; distribution of gaseous fuels through mains");
        act(modelBuilder, g, @"D.35.21", @"Manufacture of gas");
        act(modelBuilder, g, @"D.35.22", @"Distribution of gaseous fuels through mains");
        act(modelBuilder, g, @"D.35.23", @"Trade of gas through mains");
        act(modelBuilder, g, @"D.35.3", @"Steam and air conditioning supply");
        act(modelBuilder, g, @"D.35.30", @"Steam and air conditioning supply");

      g=ind(modelBuilder, @"E", @"Water supply; sewerage; waste managment and remediation activities");
        act(modelBuilder, g, @"E.36", @"Water collection, treatment and supply");
        act(modelBuilder, g, @"E.36.0", @"Water collection, treatment and supply");
        act(modelBuilder, g, @"E.36.00", @"Water collection, treatment and supply");
        act(modelBuilder, g, @"E.37", @"Sewerage");
        act(modelBuilder, g, @"E.37.0", @"Sewerage");
        act(modelBuilder, g, @"E.37.00", @"Sewerage");
        act(modelBuilder, g, @"E.38", @"Waste collection, treatment and disposal activities; materials recovery");
        act(modelBuilder, g, @"E.38.1", @"Waste collection");
        act(modelBuilder, g, @"E.38.11", @"Collection of non-hazardous waste");
        act(modelBuilder, g, @"E.38.12", @"Collection of hazardous waste");
        act(modelBuilder, g, @"E.38.2", @"Waste treatment and disposal");
        act(modelBuilder, g, @"E.38.21", @"Treatment and disposal of non-hazardous waste");
        act(modelBuilder, g, @"E.38.22", @"Treatment and disposal of hazardous waste");
        act(modelBuilder, g, @"E.38.3", @"Materials recovery");
        act(modelBuilder, g, @"E.38.31", @"Dismantling of wrecks");
        act(modelBuilder, g, @"E.38.32", @"Recovery of sorted materials");
        act(modelBuilder, g, @"E.39", @"Remediation activities and other waste management services");
        act(modelBuilder, g, @"E.39.0", @"Remediation activities and other waste management services");
        act(modelBuilder, g, @"E.39.00", @"Remediation activities and other waste management services");

      g=ind(modelBuilder, @"F", @"Construction");
        act(modelBuilder, g, @"F.41", @"Construction of buildings");
        act(modelBuilder, g, @"F.41.1", @"Development of building projects");
        act(modelBuilder, g, @"F.41.10", @"Development of building projects");
        act(modelBuilder, g, @"F.41.2", @"Construction of residential and non-residential buildings");
        act(modelBuilder, g, @"F.41.20", @"Construction of residential and non-residential buildings");
        act(modelBuilder, g, @"F.42", @"Civil engineering");
        act(modelBuilder, g, @"F.42.1", @"Construction of roads and railways");
        act(modelBuilder, g, @"F.42.11", @"Construction of roads and motorways");
        act(modelBuilder, g, @"F.42.12", @"Construction of railways and underground railways");
        act(modelBuilder, g, @"F.42.13", @"Construction of bridges and tunnels");
        act(modelBuilder, g, @"F.42.2", @"Construction of utility projects");
        act(modelBuilder, g, @"F.42.21", @"Construction of utility projects for fluids");
        act(modelBuilder, g, @"F.42.22", @"Construction of utility projects for electricity and telecommunications");
        act(modelBuilder, g, @"F.42.9", @"Construction of other civil engineering projects");
        act(modelBuilder, g, @"F.42.91", @"Construction of water projects");
        act(modelBuilder, g, @"F.42.99", @"Construction of other civil engineering projects n.e.c.");
        act(modelBuilder, g, @"F.43", @"Specialised construction activities");
        act(modelBuilder, g, @"F.43.1", @"Demolition and site preparation");
        act(modelBuilder, g, @"F.43.11", @"Demolition");
        act(modelBuilder, g, @"F.43.12", @"Site preparation");
        act(modelBuilder, g, @"F.43.13", @"Test drilling and boring");
        act(modelBuilder, g, @"F.43.2", @"Electrical, plumbing and other construction installation activities");
        act(modelBuilder, g, @"F.43.21", @"Electrical installation");
        act(modelBuilder, g, @"F.43.22", @"Plumbing, heat and air-conditioning installation");
        act(modelBuilder, g, @"F.43.29", @"Other construction installation");
        act(modelBuilder, g, @"F.43.3", @"Building completion and finishing");
        act(modelBuilder, g, @"F.43.31", @"Plastering");
        act(modelBuilder, g, @"F.43.32", @"Joinery installation");
        act(modelBuilder, g, @"F.43.33", @"Floor and wall covering");
        act(modelBuilder, g, @"F.43.34", @"Painting and glazing");
        act(modelBuilder, g, @"F.43.39", @"Other building completion and finishing");
        act(modelBuilder, g, @"F.43.9", @"Other specialised construction activities");
        act(modelBuilder, g, @"F.43.91", @"Roofing activities");
        act(modelBuilder, g, @"F.43.99", @"Other specialised construction activities n.e.c.");

      g=ind(modelBuilder, @"G", @"Wholesale and retail trade; repair of motor vehicles and motorcycles");
        act(modelBuilder, g, @"G.45", @"Wholesale and retail trade and repair of motor vehicles and motorcycles");
        act(modelBuilder, g, @"G.45.1", @"Sale of motor vehicles");
        act(modelBuilder, g, @"G.45.11", @"Sale of cars and light motor vehicles");
        act(modelBuilder, g, @"G.45.19", @"Sale of other motor vehicles");
        act(modelBuilder, g, @"G.45.2", @"Maintenance and repair of motor vehicles");
        act(modelBuilder, g, @"G.45.20", @"Maintenance and repair of motor vehicles");
        act(modelBuilder, g, @"G.45.3", @"Sale of motor vehicle parts and accessories");
        act(modelBuilder, g, @"G.45.31", @"Wholesale trade of motor vehicle parts and accessories");
        act(modelBuilder, g, @"G.45.32", @"Retail trade of motor vehicle parts and accessories");
        act(modelBuilder, g, @"G.45.4", @"Sale, maintenance and repair of motorcycles and related parts and accessories");
        act(modelBuilder, g, @"G.45.40", @"Sale, maintenance and repair of motorcycles and related parts and accessories");
        act(modelBuilder, g, @"G.46", @"Wholesale trade, except of motor vehicles and motorcycles");
        act(modelBuilder, g, @"G.46.1", @"Wholesale on a fee or contract basis");
        act(modelBuilder, g, @"G.46.11", @"Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods");
        act(modelBuilder, g, @"G.46.12", @"Agents involved in the sale of fuels, ores, metals and industrial chemicals");
        act(modelBuilder, g, @"G.46.13", @"Agents involved in the sale of timber and building materials");
        act(modelBuilder, g, @"G.46.14", @"Agents involved in the sale of machinery, industrial equipment, ships and aircraft");
        act(modelBuilder, g, @"G.46.15", @"Agents involved in the sale of furniture, household goods, hardware and ironmongery");
        act(modelBuilder, g, @"G.46.16", @"Agents involved in the sale of textiles, clothing, fur, footwear and leather goods");
        act(modelBuilder, g, @"G.46.17", @"Agents involved in the sale of food, beverages and tobacco");
        act(modelBuilder, g, @"G.46.18", @"Agents specialised in the sale of other particular products");
        act(modelBuilder, g, @"G.46.19", @"Agents involved in the sale of a variety of goods");
        act(modelBuilder, g, @"G.46.2", @"Wholesale of agricultural raw materials and live animals");
        act(modelBuilder, g, @"G.46.21", @"Wholesale of grain, unmanufactured tobacco, seeds and animal feeds");
        act(modelBuilder, g, @"G.46.22", @"Wholesale of flowers and plants");
        act(modelBuilder, g, @"G.46.23", @"Wholesale of live animals");
        act(modelBuilder, g, @"G.46.24", @"Wholesale of hides, skins and leather");
        act(modelBuilder, g, @"G.46.3", @"Wholesale of food, beverages and tobacco");
        act(modelBuilder, g, @"G.46.31", @"Wholesale of fruit and vegetables");
        act(modelBuilder, g, @"G.46.32", @"Wholesale of meat and meat products");
        act(modelBuilder, g, @"G.46.33", @"Wholesale of dairy products, eggs and edible oils and fats");
        act(modelBuilder, g, @"G.46.34", @"Wholesale of beverages");
        act(modelBuilder, g, @"G.46.35", @"Wholesale of tobacco products");
        act(modelBuilder, g, @"G.46.36", @"Wholesale of sugar and chocolate and sugar confectionery");
        act(modelBuilder, g, @"G.46.37", @"Wholesale of coffee, tea, cocoa and spices");
        act(modelBuilder, g, @"G.46.38", @"Wholesale of other food, including fish, crustaceans and molluscs");
        act(modelBuilder, g, @"G.46.39", @"Non-specialised wholesale of food, beverages and tobacco");
        act(modelBuilder, g, @"G.46.4", @"Wholesale of household goods");
        act(modelBuilder, g, @"G.46.41", @"Wholesale of textiles");
        act(modelBuilder, g, @"G.46.42", @"Wholesale of clothing and footwear");
        act(modelBuilder, g, @"G.46.43", @"Wholesale of electrical household appliances");
        act(modelBuilder, g, @"G.46.44", @"Wholesale of china and glassware and cleaning materials");
        act(modelBuilder, g, @"G.46.45", @"Wholesale of perfume and cosmetics");
        act(modelBuilder, g, @"G.46.46", @"Wholesale of pharmaceutical goods");
        act(modelBuilder, g, @"G.46.47", @"Wholesale of furniture, carpets and lighting equipment");
        act(modelBuilder, g, @"G.46.48", @"Wholesale of watches and jewellery");
        act(modelBuilder, g, @"G.46.49", @"Wholesale of other household goods");
        act(modelBuilder, g, @"G.46.5", @"Wholesale of information and communication equipment");
        act(modelBuilder, g, @"G.46.51", @"Wholesale of computers, computer peripheral equipment and software");
        act(modelBuilder, g, @"G.46.52", @"Wholesale of electronic and telecommunications equipment and parts");
        act(modelBuilder, g, @"G.46.6", @"Wholesale of other machinery, equipment and supplies");
        act(modelBuilder, g, @"G.46.61", @"Wholesale of agricultural machinery, equipment and supplies");
        act(modelBuilder, g, @"G.46.62", @"Wholesale of machine tools");
        act(modelBuilder, g, @"G.46.63", @"Wholesale of mining, construction and civil engineering machinery");
        act(modelBuilder, g, @"G.46.64", @"Wholesale of machinery for the textile industry and of sewing and knitting machines");
        act(modelBuilder, g, @"G.46.65", @"Wholesale of office furniture");
        act(modelBuilder, g, @"G.46.66", @"Wholesale of other office machinery and equipment");
        act(modelBuilder, g, @"G.46.69", @"Wholesale of other machinery and equipment");
        act(modelBuilder, g, @"G.46.7", @"Other specialised wholesale");
        act(modelBuilder, g, @"G.46.71", @"Wholesale of solid, liquid and gaseous fuels and related products");
        act(modelBuilder, g, @"G.46.72", @"Wholesale of metals and metal ores");
        act(modelBuilder, g, @"G.46.73", @"Wholesale of wood, construction materials and sanitary equipment");
        act(modelBuilder, g, @"G.46.74", @"Wholesale of hardware, plumbing and heating equipment and supplies");
        act(modelBuilder, g, @"G.46.75", @"Wholesale of chemical products");
        act(modelBuilder, g, @"G.46.76", @"Wholesale of other intermediate products");
        act(modelBuilder, g, @"G.46.77", @"Wholesale of waste and scrap");
        act(modelBuilder, g, @"G.46.9", @"Non-specialised wholesale trade");
        act(modelBuilder, g, @"G.46.90", @"Non-specialised wholesale trade");
        act(modelBuilder, g, @"G.47", @"Retail trade, except of motor vehicles and motorcycles");
        act(modelBuilder, g, @"G.47.1", @"Retail sale in non-specialised stores");
        act(modelBuilder, g, @"G.47.11", @"Retail sale in non-specialised stores with food, beverages or tobacco predominating");
        act(modelBuilder, g, @"G.47.19", @"Other retail sale in non-specialised stores");
        act(modelBuilder, g, @"G.47.2", @"Retail sale of food, beverages and tobacco in specialised stores");
        act(modelBuilder, g, @"G.47.21", @"Retail sale of fruit and vegetables in specialised stores");
        act(modelBuilder, g, @"G.47.22", @"Retail sale of meat and meat products in specialised stores");
        act(modelBuilder, g, @"G.47.23", @"Retail sale of fish, crustaceans and molluscs in specialised stores");
        act(modelBuilder, g, @"G.47.24", @"Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores");
        act(modelBuilder, g, @"G.47.25", @"Retail sale of beverages in specialised stores");
        act(modelBuilder, g, @"G.47.26", @"Retail sale of tobacco products in specialised stores");
        act(modelBuilder, g, @"G.47.29", @"Other retail sale of food in specialised stores");
        act(modelBuilder, g, @"G.47.3", @"Retail sale of automotive fuel in specialised stores");
        act(modelBuilder, g, @"G.47.30", @"Retail sale of automotive fuel in specialised stores");
        act(modelBuilder, g, @"G.47.4", @"Retail sale of information and communication equipment in specialised stores");
        act(modelBuilder, g, @"G.47.41", @"Retail sale of computers, peripheral units and software in specialised stores");
        act(modelBuilder, g, @"G.47.42", @"Retail sale of telecommunications equipment in specialised stores");
        act(modelBuilder, g, @"G.47.43", @"Retail sale of audio and video equipment in specialised stores");
        act(modelBuilder, g, @"G.47.5", @"Retail sale of other household equipment in specialised stores");
        act(modelBuilder, g, @"G.47.51", @"Retail sale of textiles in specialised stores");
        act(modelBuilder, g, @"G.47.52", @"Retail sale of hardware, paints and glass in specialised stores");
        act(modelBuilder, g, @"G.47.53", @"Retail sale of carpets, rugs, wall and floor coverings in specialised stores");
        act(modelBuilder, g, @"G.47.54", @"Retail sale of electrical household appliances in specialised stores");
        act(modelBuilder, g, @"G.47.59", @"Retail sale of furniture, lighting equipment and other household articles in specialised stores");
        act(modelBuilder, g, @"G.47.6", @"Retail sale of cultural and recreation goods in specialised stores");
        act(modelBuilder, g, @"G.47.61", @"Retail sale of books in specialised stores");
        act(modelBuilder, g, @"G.47.62", @"Retail sale of newspapers and stationery in specialised stores");
        act(modelBuilder, g, @"G.47.63", @"Retail sale of music and video recordings in specialised stores");
        act(modelBuilder, g, @"G.47.64", @"Retail sale of sporting equipment in specialised stores");
        act(modelBuilder, g, @"G.47.65", @"Retail sale of games and toys in specialised stores");
        act(modelBuilder, g, @"G.47.7", @"Retail sale of other goods in specialised stores");
        act(modelBuilder, g, @"G.47.71", @"Retail sale of clothing in specialised stores");
        act(modelBuilder, g, @"G.47.72", @"Retail sale of footwear and leather goods in specialised stores");
        act(modelBuilder, g, @"G.47.73", @"Dispensing chemist in specialised stores");
        act(modelBuilder, g, @"G.47.74", @"Retail sale of medical and orthopaedic goods in specialised stores");
        act(modelBuilder, g, @"G.47.75", @"Retail sale of cosmetic and toilet articles in specialised stores");
        act(modelBuilder, g, @"G.47.76", @"Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores");
        act(modelBuilder, g, @"G.47.77", @"Retail sale of watches and jewellery in specialised stores");
        act(modelBuilder, g, @"G.47.78", @"Other retail sale of new goods in specialised stores");
        act(modelBuilder, g, @"G.47.79", @"Retail sale of second-hand goods in stores");
        act(modelBuilder, g, @"G.47.8", @"Retail sale via stalls and markets");
        act(modelBuilder, g, @"G.47.81", @"Retail sale via stalls and markets of food, beverages and tobacco products");
        act(modelBuilder, g, @"G.47.82", @"Retail sale via stalls and markets of textiles, clothing and footwear");
        act(modelBuilder, g, @"G.47.89", @"Retail sale via stalls and markets of other goods");
        act(modelBuilder, g, @"G.47.9", @"Retail trade not in stores, stalls or markets");
        act(modelBuilder, g, @"G.47.91", @"Retail sale via mail order houses or via Internet");
        act(modelBuilder, g, @"G.47.99", @"Other retail sale not in stores, stalls or markets");

      g=ind(modelBuilder, @"H", @"Transporting and storage");
        act(modelBuilder, g, @"H.49", @"Land transport and transport via pipelines");
        act(modelBuilder, g, @"H.49.1", @"Passenger rail transport, interurban");
        act(modelBuilder, g, @"H.49.10", @"Passenger rail transport, interurban");
        act(modelBuilder, g, @"H.49.2", @"Freight rail transport");
        act(modelBuilder, g, @"H.49.20", @"Freight rail transport");
        act(modelBuilder, g, @"H.49.3", @"Other passenger land transport");
        act(modelBuilder, g, @"H.49.31", @"Urban and suburban passenger land transport");
        act(modelBuilder, g, @"H.49.32", @"Taxi operation");
        act(modelBuilder, g, @"H.49.39", @"Other passenger land transport n.e.c.");
        act(modelBuilder, g, @"H.49.4", @"Freight transport by road and removal services");
        act(modelBuilder, g, @"H.49.41", @"Freight transport by road");
        act(modelBuilder, g, @"H.49.42", @"Removal services");
        act(modelBuilder, g, @"H.49.5", @"Transport via pipeline");
        act(modelBuilder, g, @"H.49.50", @"Transport via pipeline");
        act(modelBuilder, g, @"H.50", @"Water transport");
        act(modelBuilder, g, @"H.50.1", @"Sea and coastal passenger water transport");
        act(modelBuilder, g, @"H.50.10", @"Sea and coastal passenger water transport");
        act(modelBuilder, g, @"H.50.2", @"Sea and coastal freight water transport");
        act(modelBuilder, g, @"H.50.20", @"Sea and coastal freight water transport");
        act(modelBuilder, g, @"H.50.3", @"Inland passenger water transport");
        act(modelBuilder, g, @"H.50.30", @"Inland passenger water transport");
        act(modelBuilder, g, @"H.50.4", @"Inland freight water transport");
        act(modelBuilder, g, @"H.50.40", @"Inland freight water transport");
        act(modelBuilder, g, @"H.51", @"Air transport");
        act(modelBuilder, g, @"H.51.1", @"Passenger air transport");
        act(modelBuilder, g, @"H.51.10", @"Passenger air transport");
        act(modelBuilder, g, @"H.51.2", @"Freight air transport and space transport");
        act(modelBuilder, g, @"H.51.21", @"Freight air transport");
        act(modelBuilder, g, @"H.51.22", @"Space transport");
        act(modelBuilder, g, @"H.52", @"Warehousing and support activities for transportation");
        act(modelBuilder, g, @"H.52.1", @"Warehousing and storage");
        act(modelBuilder, g, @"H.52.10", @"Warehousing and storage");
        act(modelBuilder, g, @"H.52.2", @"Support activities for transportation");
        act(modelBuilder, g, @"H.52.21", @"Service activities incidental to land transportation");
        act(modelBuilder, g, @"H.52.22", @"Service activities incidental to water transportation");
        act(modelBuilder, g, @"H.52.23", @"Service activities incidental to air transportation");
        act(modelBuilder, g, @"H.52.24", @"Cargo handling");
        act(modelBuilder, g, @"H.52.29", @"Other transportation support activities");
        act(modelBuilder, g, @"H.53", @"Postal and courier activities");
        act(modelBuilder, g, @"H.53.1", @"Postal activities under universal service obligation");
        act(modelBuilder, g, @"H.53.10", @"Postal activities under universal service obligation");
        act(modelBuilder, g, @"H.53.2", @"Other postal and courier activities");
        act(modelBuilder, g, @"H.53.20", @"Other postal and courier activities");

      g=ind(modelBuilder, @"I", @"Accommodation and food service activities");
        act(modelBuilder, g, @"I.55", @"Accommodation");
        act(modelBuilder, g, @"I.55.1", @"Hotels and similar accommodation");
        act(modelBuilder, g, @"I.55.10", @"Hotels and similar accommodation");
        act(modelBuilder, g, @"I.55.2", @"Holiday and other short-stay accommodation");
        act(modelBuilder, g, @"I.55.20", @"Holiday and other short-stay accommodation");
        act(modelBuilder, g, @"I.55.3", @"Camping grounds, recreational vehicle parks and trailer parks");
        act(modelBuilder, g, @"I.55.30", @"Camping grounds, recreational vehicle parks and trailer parks");
        act(modelBuilder, g, @"I.55.9", @"Other accommodation");
        act(modelBuilder, g, @"I.55.90", @"Other accommodation");
        act(modelBuilder, g, @"I.56", @"Food and beverage service activities");
        act(modelBuilder, g, @"I.56.1", @"Restaurants and mobile food service activities");
        act(modelBuilder, g, @"I.56.10", @"Restaurants and mobile food service activities");
        act(modelBuilder, g, @"I.56.2", @"Event catering and other food service activities");
        act(modelBuilder, g, @"I.56.21", @"Event catering activities");
        act(modelBuilder, g, @"I.56.29", @"Other food service activities");
        act(modelBuilder, g, @"I.56.3", @"Beverage serving activities");
        act(modelBuilder, g, @"I.56.30", @"Beverage serving activities");

      g=ind(modelBuilder, @"J", @"Information and communication");
        act(modelBuilder, g, @"J.58", @"Publishing activities");
        act(modelBuilder, g, @"J.58.1", @"Publishing of books, periodicals and other publishing activities");
        act(modelBuilder, g, @"J.58.11", @"Book publishing");
        act(modelBuilder, g, @"J.58.12", @"Publishing of directories and mailing lists");
        act(modelBuilder, g, @"J.58.13", @"Publishing of newspapers");
        act(modelBuilder, g, @"J.58.14", @"Publishing of journals and periodicals");
        act(modelBuilder, g, @"J.58.19", @"Other publishing activities");
        act(modelBuilder, g, @"J.58.2", @"Software publishing");
        act(modelBuilder, g, @"J.58.21", @"Publishing of computer games");
        act(modelBuilder, g, @"J.58.29", @"Other software publishing");
        act(modelBuilder, g, @"J.59", @"Motion picture, video and television programme production, sound recording and music publishing activities");
        act(modelBuilder, g, @"J.59.1", @"Motion picture, video and television programme activities");
        act(modelBuilder, g, @"J.59.11", @"Motion picture, video and television programme production activities");
        act(modelBuilder, g, @"J.59.12", @"Motion picture, video and television programme post-production activities");
        act(modelBuilder, g, @"J.59.13", @"Motion picture, video and television programme distribution activities");
        act(modelBuilder, g, @"J.59.14", @"Motion picture projection activities");
        act(modelBuilder, g, @"J.59.2", @"Sound recording and music publishing activities");
        act(modelBuilder, g, @"J.59.20", @"Sound recording and music publishing activities");
        act(modelBuilder, g, @"J.60", @"Programming and broadcasting activities");
        act(modelBuilder, g, @"J.60.1", @"Radio broadcasting");
        act(modelBuilder, g, @"J.60.10", @"Radio broadcasting");
        act(modelBuilder, g, @"J.60.2", @"Television programming and broadcasting activities");
        act(modelBuilder, g, @"J.60.20", @"Television programming and broadcasting activities");
        act(modelBuilder, g, @"J.61", @"Telecommunications");
        act(modelBuilder, g, @"J.61.1", @"Wired telecommunications activities");
        act(modelBuilder, g, @"J.61.10", @"Wired telecommunications activities");
        act(modelBuilder, g, @"J.61.2", @"Wireless telecommunications activities");
        act(modelBuilder, g, @"J.61.20", @"Wireless telecommunications activities");
        act(modelBuilder, g, @"J.61.3", @"Satellite telecommunications activities");
        act(modelBuilder, g, @"J.61.30", @"Satellite telecommunications activities");
        act(modelBuilder, g, @"J.61.9", @"Other telecommunications activities");
        act(modelBuilder, g, @"J.61.90", @"Other telecommunications activities");
        act(modelBuilder, g, @"J.62", @"Computer programming, consultancy and related activities");
        act(modelBuilder, g, @"J.62.0", @"Computer programming, consultancy and related activities");
        act(modelBuilder, g, @"J.62.01", @"Computer programming activities");
        act(modelBuilder, g, @"J.62.02", @"Computer consultancy activities");
        act(modelBuilder, g, @"J.62.03", @"Computer facilities management activities");
        act(modelBuilder, g, @"J.62.09", @"Other information technology and computer service activities");
        act(modelBuilder, g, @"J.63", @"Information service activities");
        act(modelBuilder, g, @"J.63.1", @"Data processing, hosting and related activities; web portals");
        act(modelBuilder, g, @"J.63.11", @"Data processing, hosting and related activities");
        act(modelBuilder, g, @"J.63.12", @"Web portals");
        act(modelBuilder, g, @"J.63.9", @"Other information service activities");
        act(modelBuilder, g, @"J.63.91", @"News agency activities");
        act(modelBuilder, g, @"J.63.99", @"Other information service activities n.e.c.");

      g=ind(modelBuilder, @"K", @"Financial and insurance activities");
        act(modelBuilder, g, @"K.64", @"Financial service activities, except insurance and pension funding");
        act(modelBuilder, g, @"K.64.1", @"Monetary intermediation");
        act(modelBuilder, g, @"K.64.11", @"Central banking");
        act(modelBuilder, g, @"K.64.19", @"Other monetary intermediation");
        act(modelBuilder, g, @"K.64.2", @"Activities of holding companies");
        act(modelBuilder, g, @"K.64.20", @"Activities of holding companies");
        act(modelBuilder, g, @"K.64.3", @"Trusts, funds and similar financial entities");
        act(modelBuilder, g, @"K.64.30", @"Trusts, funds and similar financial entities");
        act(modelBuilder, g, @"K.64.9", @"Other financial service activities, except insurance and pension funding");
        act(modelBuilder, g, @"K.64.91", @"Financial leasing");
        act(modelBuilder, g, @"K.64.92", @"Other credit granting");
        act(modelBuilder, g, @"K.64.99", @"Other financial service activities, except insurance and pension funding n.e.c.");
        act(modelBuilder, g, @"K.65", @"Insurance, reinsurance and pension funding, except compulsory social security");
        act(modelBuilder, g, @"K.65.1", @"Insurance");
        act(modelBuilder, g, @"K.65.11", @"Life insurance");
        act(modelBuilder, g, @"K.65.12", @"Non-life insurance");
        act(modelBuilder, g, @"K.65.2", @"Reinsurance");
        act(modelBuilder, g, @"K.65.20", @"Reinsurance");
        act(modelBuilder, g, @"K.65.3", @"Pension funding");
        act(modelBuilder, g, @"K.65.30", @"Pension funding");
        act(modelBuilder, g, @"K.66", @"Activities auxiliary to financial services and insurance activities");
        act(modelBuilder, g, @"K.66.1", @"Activities auxiliary to financial services, except insurance and pension funding");
        act(modelBuilder, g, @"K.66.11", @"Administration of financial markets");
        act(modelBuilder, g, @"K.66.12", @"Security and commodity contracts brokerage");
        act(modelBuilder, g, @"K.66.19", @"Other activities auxiliary to financial services, except insurance and pension funding");
        act(modelBuilder, g, @"K.66.2", @"Activities auxiliary to insurance and pension funding");
        act(modelBuilder, g, @"K.66.21", @"Risk and damage evaluation");
        act(modelBuilder, g, @"K.66.22", @"Activities of insurance agents and brokers");
        act(modelBuilder, g, @"K.66.29", @"Other activities auxiliary to insurance and pension funding");
        act(modelBuilder, g, @"K.66.3", @"Fund management activities");
        act(modelBuilder, g, @"K.66.30", @"Fund management activities");

      g=ind(modelBuilder, @"L", @"Real estate activities");
        act(modelBuilder, g, @"L.68", @"Real estate activities");
        act(modelBuilder, g, @"L.68.1", @"Buying and selling of own real estate");
        act(modelBuilder, g, @"L.68.10", @"Buying and selling of own real estate");
        act(modelBuilder, g, @"L.68.2", @"Renting and operating of own or leased real estate");
        act(modelBuilder, g, @"L.68.20", @"Renting and operating of own or leased real estate");
        act(modelBuilder, g, @"L.68.3", @"Real estate activities on a fee or contract basis");
        act(modelBuilder, g, @"L.68.31", @"Real estate agencies");
        act(modelBuilder, g, @"L.68.32", @"Management of real estate on a fee or contract basis");

      g=ind(modelBuilder, @"M", @"Professional, scientific and technical activities");
        act(modelBuilder, g, @"M.69", @"Legal and accounting activities");
        act(modelBuilder, g, @"M.69.1", @"Legal activities");
        act(modelBuilder, g, @"M.69.10", @"Legal activities");
        act(modelBuilder, g, @"M.69.2", @"Accounting, bookkeeping and auditing activities; tax consultancy");
        act(modelBuilder, g, @"M.69.20", @"Accounting, bookkeeping and auditing activities; tax consultancy");
        act(modelBuilder, g, @"M.70", @"Activities of head offices; management consultancy activities");
        act(modelBuilder, g, @"M.70.1", @"Activities of head offices");
        act(modelBuilder, g, @"M.70.10", @"Activities of head offices");
        act(modelBuilder, g, @"M.70.2", @"Management consultancy activities");
        act(modelBuilder, g, @"M.70.21", @"Public relations and communication activities");
        act(modelBuilder, g, @"M.70.22", @"Business and other management consultancy activities");
        act(modelBuilder, g, @"M.71", @"Architectural and engineering activities; technical testing and analysis");
        act(modelBuilder, g, @"M.71.1", @"Architectural and engineering activities and related technical consultancy");
        act(modelBuilder, g, @"M.71.11", @"Architectural activities");
        act(modelBuilder, g, @"M.71.12", @"Engineering activities and related technical consultancy");
        act(modelBuilder, g, @"M.71.2", @"Technical testing and analysis");
        act(modelBuilder, g, @"M.71.20", @"Technical testing and analysis");
        act(modelBuilder, g, @"M.72", @"Scientific research and development");
        act(modelBuilder, g, @"M.72.1", @"Research and experimental development on natural sciences and engineering");
        act(modelBuilder, g, @"M.72.11", @"Research and experimental development on biotechnology");
        act(modelBuilder, g, @"M.72.19", @"Other research and experimental development on natural sciences and engineering");
        act(modelBuilder, g, @"M.72.2", @"Research and experimental development on social sciences and humanities");
        act(modelBuilder, g, @"M.72.20", @"Research and experimental development on social sciences and humanities");
        act(modelBuilder, g, @"M.73", @"Advertising and market research");
        act(modelBuilder, g, @"M.73.1", @"Advertising");
        act(modelBuilder, g, @"M.73.11", @"Advertising agencies");
        act(modelBuilder, g, @"M.73.12", @"Media representation");
        act(modelBuilder, g, @"M.73.2", @"Market research and public opinion polling");
        act(modelBuilder, g, @"M.73.20", @"Market research and public opinion polling");
        act(modelBuilder, g, @"M.74", @"Other professional, scientific and technical activities");
        act(modelBuilder, g, @"M.74.1", @"Specialised design activities");
        act(modelBuilder, g, @"M.74.10", @"Specialised design activities");
        act(modelBuilder, g, @"M.74.2", @"Photographic activities");
        act(modelBuilder, g, @"M.74.20", @"Photographic activities");
        act(modelBuilder, g, @"M.74.3", @"Translation and interpretation activities");
        act(modelBuilder, g, @"M.74.30", @"Translation and interpretation activities");
        act(modelBuilder, g, @"M.74.9", @"Other professional, scientific and technical activities n.e.c.");
        act(modelBuilder, g, @"M.74.90", @"Other professional, scientific and technical activities n.e.c.");
        act(modelBuilder, g, @"M.75", @"Veterinary activities");
        act(modelBuilder, g, @"M.75.0", @"Veterinary activities");
        act(modelBuilder, g, @"M.75.00", @"Veterinary activities");

      g=ind(modelBuilder, @"N", @"Administrative and support service activities");
        act(modelBuilder, g, @"N.77", @"Rental and leasing activities");
        act(modelBuilder, g, @"N.77.1", @"Renting and leasing of motor vehicles");
        act(modelBuilder, g, @"N.77.11", @"Renting and leasing of cars and light motor vehicles");
        act(modelBuilder, g, @"N.77.12", @"Renting and leasing of trucks");
        act(modelBuilder, g, @"N.77.2", @"Renting and leasing of personal and household goods");
        act(modelBuilder, g, @"N.77.21", @"Renting and leasing of recreational and sports goods");
        act(modelBuilder, g, @"N.77.22", @"Renting of video tapes and disks");
        act(modelBuilder, g, @"N.77.29", @"Renting and leasing of other personal and household goods");
        act(modelBuilder, g, @"N.77.3", @"Renting and leasing of other machinery, equipment and tangible goods");
        act(modelBuilder, g, @"N.77.31", @"Renting and leasing of agricultural machinery and equipment");
        act(modelBuilder, g, @"N.77.32", @"Renting and leasing of construction and civil engineering machinery and equipment");
        act(modelBuilder, g, @"N.77.33", @"Renting and leasing of office machinery and equipment (including computers)");
        act(modelBuilder, g, @"N.77.34", @"Renting and leasing of water transport equipment");
        act(modelBuilder, g, @"N.77.35", @"Renting and leasing of air transport equipment");
        act(modelBuilder, g, @"N.77.39", @"Renting and leasing of other machinery, equipment and tangible goods n.e.c.");
        act(modelBuilder, g, @"N.77.4", @"Leasing of intellectual property and similar products, except copyrighted works");
        act(modelBuilder, g, @"N.77.40", @"Leasing of intellectual property and similar products, except copyrighted works");
        act(modelBuilder, g, @"N.78", @"Employment activities");
        act(modelBuilder, g, @"N.78.1", @"Activities of employment placement agencies");
        act(modelBuilder, g, @"N.78.10", @"Activities of employment placement agencies");
        act(modelBuilder, g, @"N.78.2", @"Temporary employment agency activities");
        act(modelBuilder, g, @"N.78.20", @"Temporary employment agency activities");
        act(modelBuilder, g, @"N.78.3", @"Other human resources provision");
        act(modelBuilder, g, @"N.78.30", @"Other human resources provision");
        act(modelBuilder, g, @"N.79", @"Travel agency, tour operator and other reservation service and related activities");
        act(modelBuilder, g, @"N.79.1", @"Travel agency and tour operator activities");
        act(modelBuilder, g, @"N.79.11", @"Travel agency activities");
        act(modelBuilder, g, @"N.79.12", @"Tour operator activities");
        act(modelBuilder, g, @"N.79.9", @"Other reservation service and related activities");
        act(modelBuilder, g, @"N.79.90", @"Other reservation service and related activities");
        act(modelBuilder, g, @"N.80", @"Security and investigation activities");
        act(modelBuilder, g, @"N.80.1", @"Private security activities");
        act(modelBuilder, g, @"N.80.10", @"Private security activities");
        act(modelBuilder, g, @"N.80.2", @"Security systems service activities");
        act(modelBuilder, g, @"N.80.20", @"Security systems service activities");
        act(modelBuilder, g, @"N.80.3", @"Investigation activities");
        act(modelBuilder, g, @"N.80.30", @"Investigation activities");
        act(modelBuilder, g, @"N.81", @"Services to buildings and landscape activities");
        act(modelBuilder, g, @"N.81.1", @"Combined facilities support activities");
        act(modelBuilder, g, @"N.81.10", @"Combined facilities support activities");
        act(modelBuilder, g, @"N.81.2", @"Cleaning activities");
        act(modelBuilder, g, @"N.81.21", @"General cleaning of buildings");
        act(modelBuilder, g, @"N.81.22", @"Other building and industrial cleaning activities");
        act(modelBuilder, g, @"N.81.29", @"Other cleaning activities");
        act(modelBuilder, g, @"N.81.3", @"Landscape service activities");
        act(modelBuilder, g, @"N.81.30", @"Landscape service activities");
        act(modelBuilder, g, @"N.82", @"Office administrative, office support and other business support activities");
        act(modelBuilder, g, @"N.82.1", @"Office administrative and support activities");
        act(modelBuilder, g, @"N.82.11", @"Combined office administrative service activities");
        act(modelBuilder, g, @"N.82.19", @"Photocopying, document preparation and other specialised office support activities");
        act(modelBuilder, g, @"N.82.2", @"Activities of call centres");
        act(modelBuilder, g, @"N.82.20", @"Activities of call centres");
        act(modelBuilder, g, @"N.82.3", @"Organisation of conventions and trade shows");
        act(modelBuilder, g, @"N.82.30", @"Organisation of conventions and trade shows");
        act(modelBuilder, g, @"N.82.9", @"Business support service activities n.e.c.");
        act(modelBuilder, g, @"N.82.92", @"Activities of collection agencies and credit bureaus");
        act(modelBuilder, g, @"N.82.91", @"Packaging activities");
        act(modelBuilder, g, @"N.82.99", @"Other business support service activities n.e.c.");

      g=ind(modelBuilder, @"O", @"Public administration and defence; compulsory social security");
        act(modelBuilder, g, @"O.84", @"Public administration and defence; compulsory social security");
        act(modelBuilder, g, @"O.84.1", @"Administration of the State and the economic and social policy of the community");
        act(modelBuilder, g, @"O.84.11", @"General public administration activities");
        act(modelBuilder, g, @"O.84.12", @"Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security");
        act(modelBuilder, g, @"O.84.13", @"Regulation of and contribution to more efficient operation of businesses");
        act(modelBuilder, g, @"O.84.2", @"Provision of services to the community as a whole");
        act(modelBuilder, g, @"O.84.21", @"Foreign affairs");
        act(modelBuilder, g, @"O.84.22", @"Defence activities");
        act(modelBuilder, g, @"O.84.23", @"Justice and judicial activities");
        act(modelBuilder, g, @"O.84.24", @"Public order and safety activities");
        act(modelBuilder, g, @"O.84.25", @"Fire service activities");
        act(modelBuilder, g, @"O.84.3", @"Compulsory social security activities");
        act(modelBuilder, g, @"O.84.30", @"Compulsory social security activities");

      g=ind(modelBuilder, @"P", @"Education");
        act(modelBuilder, g, @"P.85", @"Education");
        act(modelBuilder, g, @"P.85.1", @"Pre-primary education");
        act(modelBuilder, g, @"P.85.10", @"Pre-primary education");
        act(modelBuilder, g, @"P.85.2", @"Primary education");
        act(modelBuilder, g, @"P.85.20", @"Primary education");
        act(modelBuilder, g, @"P.85.3", @"Secondary education");
        act(modelBuilder, g, @"P.85.31", @"General secondary education");
        act(modelBuilder, g, @"P.85.32", @"Technical and vocational secondary education");
        act(modelBuilder, g, @"P.85.4", @"Higher education");
        act(modelBuilder, g, @"P.85.41", @"Post-secondary non-tertiary education");
        act(modelBuilder, g, @"P.85.42", @"Tertiary education");
        act(modelBuilder, g, @"P.85.5", @"Other education");
        act(modelBuilder, g, @"P.85.51", @"Sports and recreation education");
        act(modelBuilder, g, @"P.85.52", @"Cultural education");
        act(modelBuilder, g, @"P.85.53", @"Driving school activities");
        act(modelBuilder, g, @"P.85.59", @"Other education n.e.c.");
        act(modelBuilder, g, @"P.85.6", @"Educational support activities");
        act(modelBuilder, g, @"P.85.60", @"Educational support activities");

      g=ind(modelBuilder, @"Q", @"Human health and social work activities");
        act(modelBuilder, g, @"Q.86", @"Human health activities");
        act(modelBuilder, g, @"Q.86.1", @"Hospital activities");
        act(modelBuilder, g, @"Q.86.10", @"Hospital activities");
        act(modelBuilder, g, @"Q.86.2", @"Medical and dental practice activities");
        act(modelBuilder, g, @"Q.86.21", @"General medical practice activities");
        act(modelBuilder, g, @"Q.86.22", @"Specialist medical practice activities");
        act(modelBuilder, g, @"Q.86.23", @"Dental practice activities");
        act(modelBuilder, g, @"Q.86.9", @"Other human health activities");
        act(modelBuilder, g, @"Q.86.90", @"Other human health activities");
        act(modelBuilder, g, @"Q.87", @"Residential care activities");
        act(modelBuilder, g, @"Q.87.1", @"Residential nursing care activities");
        act(modelBuilder, g, @"Q.87.10", @"Residential nursing care activities");
        act(modelBuilder, g, @"Q.87.2", @"Residential care activities for mental retardation, mental health and substance abuse");
        act(modelBuilder, g, @"Q.87.20", @"Residential care activities for mental retardation, mental health and substance abuse");
        act(modelBuilder, g, @"Q.87.3", @"Residential care activities for the elderly and disabled");
        act(modelBuilder, g, @"Q.87.30", @"Residential care activities for the elderly and disabled");
        act(modelBuilder, g, @"Q.87.9", @"Other residential care activities");
        act(modelBuilder, g, @"Q.87.90", @"Other residential care activities");
        act(modelBuilder, g, @"Q.88", @"Social work activities without accommodation");
        act(modelBuilder, g, @"Q.88.1", @"Social work activities without accommodation for the elderly and disabled");
        act(modelBuilder, g, @"Q.88.10", @"Social work activities without accommodation for the elderly and disabled");
        act(modelBuilder, g, @"Q.88.9", @"Other social work activities without accommodation");
        act(modelBuilder, g, @"Q.88.91", @"Child day-care activities");
        act(modelBuilder, g, @"Q.88.99", @"Other social work activities without accommodation n.e.c.");

      g=ind(modelBuilder, @"R", @"Arts, entertainment and recreation");
        act(modelBuilder, g, @"R.90", @"Creative, arts and entertainment activities");
        act(modelBuilder, g, @"R.90.0", @"Creative, arts and entertainment activities");
        act(modelBuilder, g, @"R.90.01", @"Performing arts");
        act(modelBuilder, g, @"R.90.02", @"Support activities to performing arts");
        act(modelBuilder, g, @"R.90.03", @"Artistic creation");
        act(modelBuilder, g, @"R.90.04", @"Operation of arts facilities");
        act(modelBuilder, g, @"R.91", @"Libraries, archives, museums and other cultural activities");
        act(modelBuilder, g, @"R.91.0", @"Libraries, archives, museums and other cultural activities");
        act(modelBuilder, g, @"R.91.01", @"Library and archives activities");
        act(modelBuilder, g, @"R.91.02", @"Museums activities");
        act(modelBuilder, g, @"R.91.03", @"Operation of historical sites and buildings and similar visitor attractions");
        act(modelBuilder, g, @"R.91.04", @"Botanical and zoological gardens and nature reserves activities");
        act(modelBuilder, g, @"R.92", @"Gambling and betting activities");
        act(modelBuilder, g, @"R.92.0", @"Gambling and betting activities");
        act(modelBuilder, g, @"R.92.00", @"Gambling and betting activities");
        act(modelBuilder, g, @"R.93", @"Sports activities and amusement and recreation activities");
        act(modelBuilder, g, @"R.93.1", @"Sports activities");
        act(modelBuilder, g, @"R.93.11", @"Operation of sports facilities");
        act(modelBuilder, g, @"R.93.12", @"Activities of sport clubs");
        act(modelBuilder, g, @"R.93.13", @"Fitness facilities");
        act(modelBuilder, g, @"R.93.19", @"Other sports activities");
        act(modelBuilder, g, @"R.93.2", @"Amusement and recreation activities");
        act(modelBuilder, g, @"R.93.21", @"Activities of amusement parks and theme parks");
        act(modelBuilder, g, @"R.93.29", @"Other amusement and recreation activities");

      g=ind(modelBuilder, @"S", @"Other services activities");
        act(modelBuilder, g, @"S.94", @"Activities of membership organisations");
        act(modelBuilder, g, @"S.94.1", @"Activities of business, employers and professional membership organisations");
        act(modelBuilder, g, @"S.94.11", @"Activities of business and employers membership organisations");
        act(modelBuilder, g, @"S.94.12", @"Activities of professional membership organisations");
        act(modelBuilder, g, @"S.94.2", @"Activities of trade unions");
        act(modelBuilder, g, @"S.94.20", @"Activities of trade unions");
        act(modelBuilder, g, @"S.94.9", @"Activities of other membership organisations");
        act(modelBuilder, g, @"S.94.91", @"Activities of religious organisations");
        act(modelBuilder, g, @"S.94.92", @"Activities of political organisations");
        act(modelBuilder, g, @"S.94.99", @"Activities of other membership organisations n.e.c.");
        act(modelBuilder, g, @"S.95", @"Repair of computers and personal and household goods");
        act(modelBuilder, g, @"S.95.1", @"Repair of computers and communication equipment");
        act(modelBuilder, g, @"S.95.11", @"Repair of computers and peripheral equipment");
        act(modelBuilder, g, @"S.95.12", @"Repair of communication equipment");
        act(modelBuilder, g, @"S.95.2", @"Repair of personal and household goods");
        act(modelBuilder, g, @"S.95.21", @"Repair of consumer electronics");
        act(modelBuilder, g, @"S.95.22", @"Repair of household appliances and home and garden equipment");
        act(modelBuilder, g, @"S.95.23", @"Repair of footwear and leather goods");
        act(modelBuilder, g, @"S.95.24", @"Repair of furniture and home furnishings");
        act(modelBuilder, g, @"S.95.25", @"Repair of watches, clocks and jewellery");
        act(modelBuilder, g, @"S.95.29", @"Repair of other personal and household goods");
        act(modelBuilder, g, @"S.96", @"Other personal service activities");
        act(modelBuilder, g, @"S.96.0", @"Other personal service activities");
        act(modelBuilder, g, @"S.96.01", @"Washing and (dry-)cleaning of textile and fur products");
        act(modelBuilder, g, @"S.96.02", @"Hairdressing and other beauty treatment");
        act(modelBuilder, g, @"S.96.03", @"Funeral and related activities");
        act(modelBuilder, g, @"S.96.04", @"Physical well-being activities");
        act(modelBuilder, g, @"S.96.09", @"Other personal service activities n.e.c.");

      g=ind(modelBuilder, @"T", @"Activities of households as employers; undifferentiated goods-and services-producing activities of households for own use");
        act(modelBuilder, g, @"T.97", @"Activities of households as employers of domestic personnel");
        act(modelBuilder, g, @"T.97.0", @"Activities of households as employers of domestic personnel");
        act(modelBuilder, g, @"T.97.00", @"Activities of households as employers of domestic personnel");
        act(modelBuilder, g, @"T.98", @"Undifferentiated goods- and services-producing activities of private households for own use");
        act(modelBuilder, g, @"T.98.1", @"Undifferentiated goods-producing activities of private households for own use");
        act(modelBuilder, g, @"T.98.10", @"Undifferentiated goods-producing activities of private households for own use");
        act(modelBuilder, g, @"T.98.2", @"Undifferentiated service-producing activities of private households for own use");
        act(modelBuilder, g, @"T.98.20", @"Undifferentiated service-producing activities of private households for own use");

      g=ind(modelBuilder, @"U", @"Activities of extraterritorial organisations and bodies");
        act(modelBuilder, g, @"U.99", @"Activities of extraterritorial organisations and bodies");
        act(modelBuilder, g, @"U.99.0", @"Activities of extraterritorial organisations and bodies");
        act(modelBuilder, g, @"U.99.00", @"Activities of extraterritorial organisations and bodies");

      }
    }
  }
